/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppUsersRouteImport } from './routes/app/users'
import { Route as AppTasksRouteImport } from './routes/app/tasks'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppNotesRouteImport } from './routes/app/notes'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppProjectsRouteRouteImport } from './routes/app/projects/route'
import { Route as AppClientsRouteRouteImport } from './routes/app/clients/route'
import { Route as AppProjectsIndexRouteImport } from './routes/app/projects/index'
import { Route as AppClientsIndexRouteImport } from './routes/app/clients/index'
import { Route as ApiUsersIndexRouteImport } from './routes/api/users/index'
import { Route as ApiTasksIndexRouteImport } from './routes/api/tasks/index'
import { Route as ApiTagsIndexRouteImport } from './routes/api/tags/index'
import { Route as ApiSearchIndexRouteImport } from './routes/api/search/index'
import { Route as ApiProjectsIndexRouteImport } from './routes/api/projects/index'
import { Route as ApiProfileIndexRouteImport } from './routes/api/profile/index'
import { Route as ApiNotificationsIndexRouteImport } from './routes/api/notifications/index'
import { Route as ApiNotesIndexRouteImport } from './routes/api/notes/index'
import { Route as ApiDashboardIndexRouteImport } from './routes/api/dashboard/index'
import { Route as ApiClientsIndexRouteImport } from './routes/api/clients/index'
import { Route as ApiActivityIndexRouteImport } from './routes/api/activity/index'
import { Route as AppClientsClientIdRouteImport } from './routes/app/clients/$clientId'
import { Route as ApiUsersUserIdRouteImport } from './routes/api/users/$userId'
import { Route as ApiTasksTaskIdRouteImport } from './routes/api/tasks/$taskId'
import { Route as ApiTagsTagIdRouteImport } from './routes/api/tags/$tagId'
import { Route as ApiRealtimeNotificationsRouteImport } from './routes/api/realtime/notifications'
import { Route as ApiProjectsProjectIdRouteImport } from './routes/api/projects/$projectId'
import { Route as ApiProfilePasswordRouteImport } from './routes/api/profile/password'
import { Route as ApiProfileAvatarRouteImport } from './routes/api/profile/avatar'
import { Route as ApiNotesNoteIdRouteImport } from './routes/api/notes/$noteId'
import { Route as ApiCommentsCommentIdRouteImport } from './routes/api/comments/$commentId'
import { Route as ApiClientsClientIdRouteImport } from './routes/api/clients/$clientId'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as AppProjectsProjectIdRouteRouteImport } from './routes/app/projects.$projectId/route'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/app/projects.$projectId/index'
import { Route as ApiUsersMeIndexRouteImport } from './routes/api/users/me/index'
import { Route as ApiFilesFileIdIndexRouteImport } from './routes/api/files/$fileId/index'
import { Route as AppProjectsProjectIdTasksRouteImport } from './routes/app/projects.$projectId/tasks'
import { Route as AppProjectsProjectIdNotesRouteImport } from './routes/app/projects.$projectId/notes'
import { Route as AppProjectsProjectIdFilesRouteImport } from './routes/app/projects.$projectId/files'
import { Route as AppProjectsProjectIdBoardRouteImport } from './routes/app/projects.$projectId/board'
import { Route as ApiUsersMeThemeRouteImport } from './routes/api/users/me/theme'
import { Route as ApiUsersUserIdRoleRouteImport } from './routes/api/users/$userId/role'
import { Route as ApiUsersUserIdResetPasswordRouteImport } from './routes/api/users/$userId/reset-password'
import { Route as ApiTasksTaskIdMoveRouteImport } from './routes/api/tasks/$taskId/move'
import { Route as ApiTasksTaskIdActivityRouteImport } from './routes/api/tasks/$taskId/activity'
import { Route as ApiTagsTagIdDetachRouteImport } from './routes/api/tags/$tagId/detach'
import { Route as ApiTagsTagIdAttachRouteImport } from './routes/api/tags/$tagId/attach'
import { Route as ApiRealtimeProjectsProjectIdRouteImport } from './routes/api/realtime/projects.$projectId'
import { Route as ApiProjectsProjectIdFilesRouteImport } from './routes/api/projects/$projectId/files'
import { Route as ApiProjectsProjectIdArchiveRouteImport } from './routes/api/projects/$projectId/archive'
import { Route as ApiProjectsProjectIdActivityRouteImport } from './routes/api/projects/$projectId/activity'
import { Route as ApiNotificationsNotificationIdReadRouteImport } from './routes/api/notifications/$notificationId/read'
import { Route as ApiNotesNoteIdSecretRouteImport } from './routes/api/notes/$noteId/secret'
import { Route as ApiFilesFileIdDownloadRouteImport } from './routes/api/files/$fileId/download'
import { Route as ApiClientsClientIdActivityRouteImport } from './routes/api/clients/$clientId/activity'
import { Route as ApiTasksTaskIdCommentsIndexRouteImport } from './routes/api/tasks/$taskId/comments/index'
import { Route as ApiProjectsProjectIdMembersIndexRouteImport } from './routes/api/projects/$projectId/members/index'
import { Route as ApiProjectsProjectIdMembersUserIdRouteImport } from './routes/api/projects/$projectId/members/$userId'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsRouteRoute = AppProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientsRouteRoute = AppClientsRouteRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsRouteRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClientsRouteRoute,
} as any)
const ApiUsersIndexRoute = ApiUsersIndexRouteImport.update({
  id: '/api/users/',
  path: '/api/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksIndexRoute = ApiTasksIndexRouteImport.update({
  id: '/api/tasks/',
  path: '/api/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTagsIndexRoute = ApiTagsIndexRouteImport.update({
  id: '/api/tags/',
  path: '/api/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchIndexRoute = ApiSearchIndexRouteImport.update({
  id: '/api/search/',
  path: '/api/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIndexRoute = ApiProjectsIndexRouteImport.update({
  id: '/api/projects/',
  path: '/api/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileIndexRoute = ApiProfileIndexRouteImport.update({
  id: '/api/profile/',
  path: '/api/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsIndexRoute = ApiNotificationsIndexRouteImport.update({
  id: '/api/notifications/',
  path: '/api/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesIndexRoute = ApiNotesIndexRouteImport.update({
  id: '/api/notes/',
  path: '/api/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardIndexRoute = ApiDashboardIndexRouteImport.update({
  id: '/api/dashboard/',
  path: '/api/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientsIndexRoute = ApiClientsIndexRouteImport.update({
  id: '/api/clients/',
  path: '/api/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActivityIndexRoute = ApiActivityIndexRouteImport.update({
  id: '/api/activity/',
  path: '/api/activity/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => AppClientsRouteRoute,
} as any)
const ApiUsersUserIdRoute = ApiUsersUserIdRouteImport.update({
  id: '/api/users/$userId',
  path: '/api/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksTaskIdRoute = ApiTasksTaskIdRouteImport.update({
  id: '/api/tasks/$taskId',
  path: '/api/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTagsTagIdRoute = ApiTagsTagIdRouteImport.update({
  id: '/api/tags/$tagId',
  path: '/api/tags/$tagId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeNotificationsRoute =
  ApiRealtimeNotificationsRouteImport.update({
    id: '/api/realtime/notifications',
    path: '/api/realtime/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsProjectIdRoute = ApiProjectsProjectIdRouteImport.update({
  id: '/api/projects/$projectId',
  path: '/api/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilePasswordRoute = ApiProfilePasswordRouteImport.update({
  id: '/api/profile/password',
  path: '/api/profile/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileAvatarRoute = ApiProfileAvatarRouteImport.update({
  id: '/api/profile/avatar',
  path: '/api/profile/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesNoteIdRoute = ApiNotesNoteIdRouteImport.update({
  id: '/api/notes/$noteId',
  path: '/api/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentsCommentIdRoute = ApiCommentsCommentIdRouteImport.update({
  id: '/api/comments/$commentId',
  path: '/api/comments/$commentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientsClientIdRoute = ApiClientsClientIdRouteImport.update({
  id: '/api/clients/$clientId',
  path: '/api/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsProjectIdRouteRoute =
  AppProjectsProjectIdRouteRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AppProjectsRouteRoute,
  } as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const ApiUsersMeIndexRoute = ApiUsersMeIndexRouteImport.update({
  id: '/api/users/me/',
  path: '/api/users/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesFileIdIndexRoute = ApiFilesFileIdIndexRouteImport.update({
  id: '/api/files/$fileId/',
  path: '/api/files/$fileId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsProjectIdTasksRoute =
  AppProjectsProjectIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdNotesRoute =
  AppProjectsProjectIdNotesRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdFilesRoute =
  AppProjectsProjectIdFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdBoardRoute =
  AppProjectsProjectIdBoardRouteImport.update({
    id: '/board',
    path: '/board',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const ApiUsersMeThemeRoute = ApiUsersMeThemeRouteImport.update({
  id: '/api/users/me/theme',
  path: '/api/users/me/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersUserIdRoleRoute = ApiUsersUserIdRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => ApiUsersUserIdRoute,
} as any)
const ApiUsersUserIdResetPasswordRoute =
  ApiUsersUserIdResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => ApiUsersUserIdRoute,
  } as any)
const ApiTasksTaskIdMoveRoute = ApiTasksTaskIdMoveRouteImport.update({
  id: '/move',
  path: '/move',
  getParentRoute: () => ApiTasksTaskIdRoute,
} as any)
const ApiTasksTaskIdActivityRoute = ApiTasksTaskIdActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ApiTasksTaskIdRoute,
} as any)
const ApiTagsTagIdDetachRoute = ApiTagsTagIdDetachRouteImport.update({
  id: '/detach',
  path: '/detach',
  getParentRoute: () => ApiTagsTagIdRoute,
} as any)
const ApiTagsTagIdAttachRoute = ApiTagsTagIdAttachRouteImport.update({
  id: '/attach',
  path: '/attach',
  getParentRoute: () => ApiTagsTagIdRoute,
} as any)
const ApiRealtimeProjectsProjectIdRoute =
  ApiRealtimeProjectsProjectIdRouteImport.update({
    id: '/api/realtime/projects/$projectId',
    path: '/api/realtime/projects/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsProjectIdFilesRoute =
  ApiProjectsProjectIdFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => ApiProjectsProjectIdRoute,
  } as any)
const ApiProjectsProjectIdArchiveRoute =
  ApiProjectsProjectIdArchiveRouteImport.update({
    id: '/archive',
    path: '/archive',
    getParentRoute: () => ApiProjectsProjectIdRoute,
  } as any)
const ApiProjectsProjectIdActivityRoute =
  ApiProjectsProjectIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => ApiProjectsProjectIdRoute,
  } as any)
const ApiNotificationsNotificationIdReadRoute =
  ApiNotificationsNotificationIdReadRouteImport.update({
    id: '/api/notifications/$notificationId/read',
    path: '/api/notifications/$notificationId/read',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiNotesNoteIdSecretRoute = ApiNotesNoteIdSecretRouteImport.update({
  id: '/secret',
  path: '/secret',
  getParentRoute: () => ApiNotesNoteIdRoute,
} as any)
const ApiFilesFileIdDownloadRoute = ApiFilesFileIdDownloadRouteImport.update({
  id: '/api/files/$fileId/download',
  path: '/api/files/$fileId/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientsClientIdActivityRoute =
  ApiClientsClientIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => ApiClientsClientIdRoute,
  } as any)
const ApiTasksTaskIdCommentsIndexRoute =
  ApiTasksTaskIdCommentsIndexRouteImport.update({
    id: '/comments/',
    path: '/comments/',
    getParentRoute: () => ApiTasksTaskIdRoute,
  } as any)
const ApiProjectsProjectIdMembersIndexRoute =
  ApiProjectsProjectIdMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => ApiProjectsProjectIdRoute,
  } as any)
const ApiProjectsProjectIdMembersUserIdRoute =
  ApiProjectsProjectIdMembersUserIdRouteImport.update({
    id: '/members/$userId',
    path: '/members/$userId',
    getParentRoute: () => ApiProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/app/clients': typeof AppClientsRouteRouteWithChildren
  '/app/projects': typeof AppProjectsRouteRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/notes': typeof AppNotesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/users': typeof AppUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/clients/$clientId': typeof ApiClientsClientIdRouteWithChildren
  '/api/comments/$commentId': typeof ApiCommentsCommentIdRoute
  '/api/notes/$noteId': typeof ApiNotesNoteIdRouteWithChildren
  '/api/profile/avatar': typeof ApiProfileAvatarRoute
  '/api/profile/password': typeof ApiProfilePasswordRoute
  '/api/projects/$projectId': typeof ApiProjectsProjectIdRouteWithChildren
  '/api/realtime/notifications': typeof ApiRealtimeNotificationsRoute
  '/api/tags/$tagId': typeof ApiTagsTagIdRouteWithChildren
  '/api/tasks/$taskId': typeof ApiTasksTaskIdRouteWithChildren
  '/api/users/$userId': typeof ApiUsersUserIdRouteWithChildren
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
  '/api/activity': typeof ApiActivityIndexRoute
  '/api/clients': typeof ApiClientsIndexRoute
  '/api/dashboard': typeof ApiDashboardIndexRoute
  '/api/notes': typeof ApiNotesIndexRoute
  '/api/notifications': typeof ApiNotificationsIndexRoute
  '/api/profile': typeof ApiProfileIndexRoute
  '/api/projects': typeof ApiProjectsIndexRoute
  '/api/search': typeof ApiSearchIndexRoute
  '/api/tags': typeof ApiTagsIndexRoute
  '/api/tasks': typeof ApiTasksIndexRoute
  '/api/users': typeof ApiUsersIndexRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/api/clients/$clientId/activity': typeof ApiClientsClientIdActivityRoute
  '/api/files/$fileId/download': typeof ApiFilesFileIdDownloadRoute
  '/api/notes/$noteId/secret': typeof ApiNotesNoteIdSecretRoute
  '/api/notifications/$notificationId/read': typeof ApiNotificationsNotificationIdReadRoute
  '/api/projects/$projectId/activity': typeof ApiProjectsProjectIdActivityRoute
  '/api/projects/$projectId/archive': typeof ApiProjectsProjectIdArchiveRoute
  '/api/projects/$projectId/files': typeof ApiProjectsProjectIdFilesRoute
  '/api/realtime/projects/$projectId': typeof ApiRealtimeProjectsProjectIdRoute
  '/api/tags/$tagId/attach': typeof ApiTagsTagIdAttachRoute
  '/api/tags/$tagId/detach': typeof ApiTagsTagIdDetachRoute
  '/api/tasks/$taskId/activity': typeof ApiTasksTaskIdActivityRoute
  '/api/tasks/$taskId/move': typeof ApiTasksTaskIdMoveRoute
  '/api/users/$userId/reset-password': typeof ApiUsersUserIdResetPasswordRoute
  '/api/users/$userId/role': typeof ApiUsersUserIdRoleRoute
  '/api/users/me/theme': typeof ApiUsersMeThemeRoute
  '/app/projects/$projectId/board': typeof AppProjectsProjectIdBoardRoute
  '/app/projects/$projectId/files': typeof AppProjectsProjectIdFilesRoute
  '/app/projects/$projectId/notes': typeof AppProjectsProjectIdNotesRoute
  '/app/projects/$projectId/tasks': typeof AppProjectsProjectIdTasksRoute
  '/api/files/$fileId': typeof ApiFilesFileIdIndexRoute
  '/api/users/me': typeof ApiUsersMeIndexRoute
  '/app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/api/projects/$projectId/members/$userId': typeof ApiProjectsProjectIdMembersUserIdRoute
  '/api/projects/$projectId/members': typeof ApiProjectsProjectIdMembersIndexRoute
  '/api/tasks/$taskId/comments': typeof ApiTasksTaskIdCommentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/notes': typeof AppNotesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/users': typeof AppUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/clients/$clientId': typeof ApiClientsClientIdRouteWithChildren
  '/api/comments/$commentId': typeof ApiCommentsCommentIdRoute
  '/api/notes/$noteId': typeof ApiNotesNoteIdRouteWithChildren
  '/api/profile/avatar': typeof ApiProfileAvatarRoute
  '/api/profile/password': typeof ApiProfilePasswordRoute
  '/api/projects/$projectId': typeof ApiProjectsProjectIdRouteWithChildren
  '/api/realtime/notifications': typeof ApiRealtimeNotificationsRoute
  '/api/tags/$tagId': typeof ApiTagsTagIdRouteWithChildren
  '/api/tasks/$taskId': typeof ApiTasksTaskIdRouteWithChildren
  '/api/users/$userId': typeof ApiUsersUserIdRouteWithChildren
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
  '/api/activity': typeof ApiActivityIndexRoute
  '/api/clients': typeof ApiClientsIndexRoute
  '/api/dashboard': typeof ApiDashboardIndexRoute
  '/api/notes': typeof ApiNotesIndexRoute
  '/api/notifications': typeof ApiNotificationsIndexRoute
  '/api/profile': typeof ApiProfileIndexRoute
  '/api/projects': typeof ApiProjectsIndexRoute
  '/api/search': typeof ApiSearchIndexRoute
  '/api/tags': typeof ApiTagsIndexRoute
  '/api/tasks': typeof ApiTasksIndexRoute
  '/api/users': typeof ApiUsersIndexRoute
  '/app/clients': typeof AppClientsIndexRoute
  '/app/projects': typeof AppProjectsIndexRoute
  '/api/clients/$clientId/activity': typeof ApiClientsClientIdActivityRoute
  '/api/files/$fileId/download': typeof ApiFilesFileIdDownloadRoute
  '/api/notes/$noteId/secret': typeof ApiNotesNoteIdSecretRoute
  '/api/notifications/$notificationId/read': typeof ApiNotificationsNotificationIdReadRoute
  '/api/projects/$projectId/activity': typeof ApiProjectsProjectIdActivityRoute
  '/api/projects/$projectId/archive': typeof ApiProjectsProjectIdArchiveRoute
  '/api/projects/$projectId/files': typeof ApiProjectsProjectIdFilesRoute
  '/api/realtime/projects/$projectId': typeof ApiRealtimeProjectsProjectIdRoute
  '/api/tags/$tagId/attach': typeof ApiTagsTagIdAttachRoute
  '/api/tags/$tagId/detach': typeof ApiTagsTagIdDetachRoute
  '/api/tasks/$taskId/activity': typeof ApiTasksTaskIdActivityRoute
  '/api/tasks/$taskId/move': typeof ApiTasksTaskIdMoveRoute
  '/api/users/$userId/reset-password': typeof ApiUsersUserIdResetPasswordRoute
  '/api/users/$userId/role': typeof ApiUsersUserIdRoleRoute
  '/api/users/me/theme': typeof ApiUsersMeThemeRoute
  '/app/projects/$projectId/board': typeof AppProjectsProjectIdBoardRoute
  '/app/projects/$projectId/files': typeof AppProjectsProjectIdFilesRoute
  '/app/projects/$projectId/notes': typeof AppProjectsProjectIdNotesRoute
  '/app/projects/$projectId/tasks': typeof AppProjectsProjectIdTasksRoute
  '/api/files/$fileId': typeof ApiFilesFileIdIndexRoute
  '/api/users/me': typeof ApiUsersMeIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/api/projects/$projectId/members/$userId': typeof ApiProjectsProjectIdMembersUserIdRoute
  '/api/projects/$projectId/members': typeof ApiProjectsProjectIdMembersIndexRoute
  '/api/tasks/$taskId/comments': typeof ApiTasksTaskIdCommentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/app/clients': typeof AppClientsRouteRouteWithChildren
  '/app/projects': typeof AppProjectsRouteRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/notes': typeof AppNotesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/users': typeof AppUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/clients/$clientId': typeof ApiClientsClientIdRouteWithChildren
  '/api/comments/$commentId': typeof ApiCommentsCommentIdRoute
  '/api/notes/$noteId': typeof ApiNotesNoteIdRouteWithChildren
  '/api/profile/avatar': typeof ApiProfileAvatarRoute
  '/api/profile/password': typeof ApiProfilePasswordRoute
  '/api/projects/$projectId': typeof ApiProjectsProjectIdRouteWithChildren
  '/api/realtime/notifications': typeof ApiRealtimeNotificationsRoute
  '/api/tags/$tagId': typeof ApiTagsTagIdRouteWithChildren
  '/api/tasks/$taskId': typeof ApiTasksTaskIdRouteWithChildren
  '/api/users/$userId': typeof ApiUsersUserIdRouteWithChildren
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
  '/api/activity/': typeof ApiActivityIndexRoute
  '/api/clients/': typeof ApiClientsIndexRoute
  '/api/dashboard/': typeof ApiDashboardIndexRoute
  '/api/notes/': typeof ApiNotesIndexRoute
  '/api/notifications/': typeof ApiNotificationsIndexRoute
  '/api/profile/': typeof ApiProfileIndexRoute
  '/api/projects/': typeof ApiProjectsIndexRoute
  '/api/search/': typeof ApiSearchIndexRoute
  '/api/tags/': typeof ApiTagsIndexRoute
  '/api/tasks/': typeof ApiTasksIndexRoute
  '/api/users/': typeof ApiUsersIndexRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/api/clients/$clientId/activity': typeof ApiClientsClientIdActivityRoute
  '/api/files/$fileId/download': typeof ApiFilesFileIdDownloadRoute
  '/api/notes/$noteId/secret': typeof ApiNotesNoteIdSecretRoute
  '/api/notifications/$notificationId/read': typeof ApiNotificationsNotificationIdReadRoute
  '/api/projects/$projectId/activity': typeof ApiProjectsProjectIdActivityRoute
  '/api/projects/$projectId/archive': typeof ApiProjectsProjectIdArchiveRoute
  '/api/projects/$projectId/files': typeof ApiProjectsProjectIdFilesRoute
  '/api/realtime/projects/$projectId': typeof ApiRealtimeProjectsProjectIdRoute
  '/api/tags/$tagId/attach': typeof ApiTagsTagIdAttachRoute
  '/api/tags/$tagId/detach': typeof ApiTagsTagIdDetachRoute
  '/api/tasks/$taskId/activity': typeof ApiTasksTaskIdActivityRoute
  '/api/tasks/$taskId/move': typeof ApiTasksTaskIdMoveRoute
  '/api/users/$userId/reset-password': typeof ApiUsersUserIdResetPasswordRoute
  '/api/users/$userId/role': typeof ApiUsersUserIdRoleRoute
  '/api/users/me/theme': typeof ApiUsersMeThemeRoute
  '/app/projects/$projectId/board': typeof AppProjectsProjectIdBoardRoute
  '/app/projects/$projectId/files': typeof AppProjectsProjectIdFilesRoute
  '/app/projects/$projectId/notes': typeof AppProjectsProjectIdNotesRoute
  '/app/projects/$projectId/tasks': typeof AppProjectsProjectIdTasksRoute
  '/api/files/$fileId/': typeof ApiFilesFileIdIndexRoute
  '/api/users/me/': typeof ApiUsersMeIndexRoute
  '/app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/api/projects/$projectId/members/$userId': typeof ApiProjectsProjectIdMembersUserIdRoute
  '/api/projects/$projectId/members/': typeof ApiProjectsProjectIdMembersIndexRoute
  '/api/tasks/$taskId/comments/': typeof ApiTasksTaskIdCommentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/clients'
    | '/app/projects'
    | '/app/dashboard'
    | '/app/notes'
    | '/app/profile'
    | '/app/settings'
    | '/app/tasks'
    | '/app/users'
    | '/auth/login'
    | '/app/projects/$projectId'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/clients/$clientId'
    | '/api/comments/$commentId'
    | '/api/notes/$noteId'
    | '/api/profile/avatar'
    | '/api/profile/password'
    | '/api/projects/$projectId'
    | '/api/realtime/notifications'
    | '/api/tags/$tagId'
    | '/api/tasks/$taskId'
    | '/api/users/$userId'
    | '/app/clients/$clientId'
    | '/api/activity'
    | '/api/clients'
    | '/api/dashboard'
    | '/api/notes'
    | '/api/notifications'
    | '/api/profile'
    | '/api/projects'
    | '/api/search'
    | '/api/tags'
    | '/api/tasks'
    | '/api/users'
    | '/app/clients/'
    | '/app/projects/'
    | '/api/clients/$clientId/activity'
    | '/api/files/$fileId/download'
    | '/api/notes/$noteId/secret'
    | '/api/notifications/$notificationId/read'
    | '/api/projects/$projectId/activity'
    | '/api/projects/$projectId/archive'
    | '/api/projects/$projectId/files'
    | '/api/realtime/projects/$projectId'
    | '/api/tags/$tagId/attach'
    | '/api/tags/$tagId/detach'
    | '/api/tasks/$taskId/activity'
    | '/api/tasks/$taskId/move'
    | '/api/users/$userId/reset-password'
    | '/api/users/$userId/role'
    | '/api/users/me/theme'
    | '/app/projects/$projectId/board'
    | '/app/projects/$projectId/files'
    | '/app/projects/$projectId/notes'
    | '/app/projects/$projectId/tasks'
    | '/api/files/$fileId'
    | '/api/users/me'
    | '/app/projects/$projectId/'
    | '/api/projects/$projectId/members/$userId'
    | '/api/projects/$projectId/members'
    | '/api/tasks/$taskId/comments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/app/dashboard'
    | '/app/notes'
    | '/app/profile'
    | '/app/settings'
    | '/app/tasks'
    | '/app/users'
    | '/auth/login'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/clients/$clientId'
    | '/api/comments/$commentId'
    | '/api/notes/$noteId'
    | '/api/profile/avatar'
    | '/api/profile/password'
    | '/api/projects/$projectId'
    | '/api/realtime/notifications'
    | '/api/tags/$tagId'
    | '/api/tasks/$taskId'
    | '/api/users/$userId'
    | '/app/clients/$clientId'
    | '/api/activity'
    | '/api/clients'
    | '/api/dashboard'
    | '/api/notes'
    | '/api/notifications'
    | '/api/profile'
    | '/api/projects'
    | '/api/search'
    | '/api/tags'
    | '/api/tasks'
    | '/api/users'
    | '/app/clients'
    | '/app/projects'
    | '/api/clients/$clientId/activity'
    | '/api/files/$fileId/download'
    | '/api/notes/$noteId/secret'
    | '/api/notifications/$notificationId/read'
    | '/api/projects/$projectId/activity'
    | '/api/projects/$projectId/archive'
    | '/api/projects/$projectId/files'
    | '/api/realtime/projects/$projectId'
    | '/api/tags/$tagId/attach'
    | '/api/tags/$tagId/detach'
    | '/api/tasks/$taskId/activity'
    | '/api/tasks/$taskId/move'
    | '/api/users/$userId/reset-password'
    | '/api/users/$userId/role'
    | '/api/users/me/theme'
    | '/app/projects/$projectId/board'
    | '/app/projects/$projectId/files'
    | '/app/projects/$projectId/notes'
    | '/app/projects/$projectId/tasks'
    | '/api/files/$fileId'
    | '/api/users/me'
    | '/app/projects/$projectId'
    | '/api/projects/$projectId/members/$userId'
    | '/api/projects/$projectId/members'
    | '/api/tasks/$taskId/comments'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/clients'
    | '/app/projects'
    | '/app/dashboard'
    | '/app/notes'
    | '/app/profile'
    | '/app/settings'
    | '/app/tasks'
    | '/app/users'
    | '/auth/login'
    | '/app/projects/$projectId'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/clients/$clientId'
    | '/api/comments/$commentId'
    | '/api/notes/$noteId'
    | '/api/profile/avatar'
    | '/api/profile/password'
    | '/api/projects/$projectId'
    | '/api/realtime/notifications'
    | '/api/tags/$tagId'
    | '/api/tasks/$taskId'
    | '/api/users/$userId'
    | '/app/clients/$clientId'
    | '/api/activity/'
    | '/api/clients/'
    | '/api/dashboard/'
    | '/api/notes/'
    | '/api/notifications/'
    | '/api/profile/'
    | '/api/projects/'
    | '/api/search/'
    | '/api/tags/'
    | '/api/tasks/'
    | '/api/users/'
    | '/app/clients/'
    | '/app/projects/'
    | '/api/clients/$clientId/activity'
    | '/api/files/$fileId/download'
    | '/api/notes/$noteId/secret'
    | '/api/notifications/$notificationId/read'
    | '/api/projects/$projectId/activity'
    | '/api/projects/$projectId/archive'
    | '/api/projects/$projectId/files'
    | '/api/realtime/projects/$projectId'
    | '/api/tags/$tagId/attach'
    | '/api/tags/$tagId/detach'
    | '/api/tasks/$taskId/activity'
    | '/api/tasks/$taskId/move'
    | '/api/users/$userId/reset-password'
    | '/api/users/$userId/role'
    | '/api/users/me/theme'
    | '/app/projects/$projectId/board'
    | '/app/projects/$projectId/files'
    | '/app/projects/$projectId/notes'
    | '/app/projects/$projectId/tasks'
    | '/api/files/$fileId/'
    | '/api/users/me/'
    | '/app/projects/$projectId/'
    | '/api/projects/$projectId/members/$userId'
    | '/api/projects/$projectId/members/'
    | '/api/tasks/$taskId/comments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiClientsClientIdRoute: typeof ApiClientsClientIdRouteWithChildren
  ApiCommentsCommentIdRoute: typeof ApiCommentsCommentIdRoute
  ApiNotesNoteIdRoute: typeof ApiNotesNoteIdRouteWithChildren
  ApiProfileAvatarRoute: typeof ApiProfileAvatarRoute
  ApiProfilePasswordRoute: typeof ApiProfilePasswordRoute
  ApiProjectsProjectIdRoute: typeof ApiProjectsProjectIdRouteWithChildren
  ApiRealtimeNotificationsRoute: typeof ApiRealtimeNotificationsRoute
  ApiTagsTagIdRoute: typeof ApiTagsTagIdRouteWithChildren
  ApiTasksTaskIdRoute: typeof ApiTasksTaskIdRouteWithChildren
  ApiUsersUserIdRoute: typeof ApiUsersUserIdRouteWithChildren
  ApiActivityIndexRoute: typeof ApiActivityIndexRoute
  ApiClientsIndexRoute: typeof ApiClientsIndexRoute
  ApiDashboardIndexRoute: typeof ApiDashboardIndexRoute
  ApiNotesIndexRoute: typeof ApiNotesIndexRoute
  ApiNotificationsIndexRoute: typeof ApiNotificationsIndexRoute
  ApiProfileIndexRoute: typeof ApiProfileIndexRoute
  ApiProjectsIndexRoute: typeof ApiProjectsIndexRoute
  ApiSearchIndexRoute: typeof ApiSearchIndexRoute
  ApiTagsIndexRoute: typeof ApiTagsIndexRoute
  ApiTasksIndexRoute: typeof ApiTasksIndexRoute
  ApiUsersIndexRoute: typeof ApiUsersIndexRoute
  ApiFilesFileIdDownloadRoute: typeof ApiFilesFileIdDownloadRoute
  ApiNotificationsNotificationIdReadRoute: typeof ApiNotificationsNotificationIdReadRoute
  ApiRealtimeProjectsProjectIdRoute: typeof ApiRealtimeProjectsProjectIdRoute
  ApiUsersMeThemeRoute: typeof ApiUsersMeThemeRoute
  ApiFilesFileIdIndexRoute: typeof ApiFilesFileIdIndexRoute
  ApiUsersMeIndexRoute: typeof ApiUsersMeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppProjectsRouteRoute
    }
    '/app/clients/': {
      id: '/app/clients/'
      path: '/'
      fullPath: '/app/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppClientsRouteRoute
    }
    '/api/users/': {
      id: '/api/users/'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/': {
      id: '/api/tasks/'
      path: '/api/tasks'
      fullPath: '/api/tasks'
      preLoaderRoute: typeof ApiTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tags/': {
      id: '/api/tags/'
      path: '/api/tags'
      fullPath: '/api/tags'
      preLoaderRoute: typeof ApiTagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search/': {
      id: '/api/search/'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/': {
      id: '/api/projects/'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/': {
      id: '/api/profile/'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/': {
      id: '/api/notifications/'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes/': {
      id: '/api/notes/'
      path: '/api/notes'
      fullPath: '/api/notes'
      preLoaderRoute: typeof ApiNotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/': {
      id: '/api/dashboard/'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clients/': {
      id: '/api/clients/'
      path: '/api/clients'
      fullPath: '/api/clients'
      preLoaderRoute: typeof ApiClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/activity/': {
      id: '/api/activity/'
      path: '/api/activity'
      fullPath: '/api/activity'
      preLoaderRoute: typeof ApiActivityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/clients/$clientId': {
      id: '/app/clients/$clientId'
      path: '/$clientId'
      fullPath: '/app/clients/$clientId'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppClientsRouteRoute
    }
    '/api/users/$userId': {
      id: '/api/users/$userId'
      path: '/api/users/$userId'
      fullPath: '/api/users/$userId'
      preLoaderRoute: typeof ApiUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/$taskId': {
      id: '/api/tasks/$taskId'
      path: '/api/tasks/$taskId'
      fullPath: '/api/tasks/$taskId'
      preLoaderRoute: typeof ApiTasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tags/$tagId': {
      id: '/api/tags/$tagId'
      path: '/api/tags/$tagId'
      fullPath: '/api/tags/$tagId'
      preLoaderRoute: typeof ApiTagsTagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime/notifications': {
      id: '/api/realtime/notifications'
      path: '/api/realtime/notifications'
      fullPath: '/api/realtime/notifications'
      preLoaderRoute: typeof ApiRealtimeNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$projectId': {
      id: '/api/projects/$projectId'
      path: '/api/projects/$projectId'
      fullPath: '/api/projects/$projectId'
      preLoaderRoute: typeof ApiProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/password': {
      id: '/api/profile/password'
      path: '/api/profile/password'
      fullPath: '/api/profile/password'
      preLoaderRoute: typeof ApiProfilePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/avatar': {
      id: '/api/profile/avatar'
      path: '/api/profile/avatar'
      fullPath: '/api/profile/avatar'
      preLoaderRoute: typeof ApiProfileAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes/$noteId': {
      id: '/api/notes/$noteId'
      path: '/api/notes/$noteId'
      fullPath: '/api/notes/$noteId'
      preLoaderRoute: typeof ApiNotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comments/$commentId': {
      id: '/api/comments/$commentId'
      path: '/api/comments/$commentId'
      fullPath: '/api/comments/$commentId'
      preLoaderRoute: typeof ApiCommentsCommentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clients/$clientId': {
      id: '/api/clients/$clientId'
      path: '/api/clients/$clientId'
      fullPath: '/api/clients/$clientId'
      preLoaderRoute: typeof ApiClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteRouteImport
      parentRoute: typeof AppProjectsRouteRoute
    }
    '/app/projects/$projectId/': {
      id: '/app/projects/$projectId/'
      path: '/'
      fullPath: '/app/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/api/users/me/': {
      id: '/api/users/me/'
      path: '/api/users/me'
      fullPath: '/api/users/me'
      preLoaderRoute: typeof ApiUsersMeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$fileId/': {
      id: '/api/files/$fileId/'
      path: '/api/files/$fileId'
      fullPath: '/api/files/$fileId'
      preLoaderRoute: typeof ApiFilesFileIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects/$projectId/tasks': {
      id: '/app/projects/$projectId/tasks'
      path: '/tasks'
      fullPath: '/app/projects/$projectId/tasks'
      preLoaderRoute: typeof AppProjectsProjectIdTasksRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/app/projects/$projectId/notes': {
      id: '/app/projects/$projectId/notes'
      path: '/notes'
      fullPath: '/app/projects/$projectId/notes'
      preLoaderRoute: typeof AppProjectsProjectIdNotesRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/app/projects/$projectId/files': {
      id: '/app/projects/$projectId/files'
      path: '/files'
      fullPath: '/app/projects/$projectId/files'
      preLoaderRoute: typeof AppProjectsProjectIdFilesRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/app/projects/$projectId/board': {
      id: '/app/projects/$projectId/board'
      path: '/board'
      fullPath: '/app/projects/$projectId/board'
      preLoaderRoute: typeof AppProjectsProjectIdBoardRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/api/users/me/theme': {
      id: '/api/users/me/theme'
      path: '/api/users/me/theme'
      fullPath: '/api/users/me/theme'
      preLoaderRoute: typeof ApiUsersMeThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$userId/role': {
      id: '/api/users/$userId/role'
      path: '/role'
      fullPath: '/api/users/$userId/role'
      preLoaderRoute: typeof ApiUsersUserIdRoleRouteImport
      parentRoute: typeof ApiUsersUserIdRoute
    }
    '/api/users/$userId/reset-password': {
      id: '/api/users/$userId/reset-password'
      path: '/reset-password'
      fullPath: '/api/users/$userId/reset-password'
      preLoaderRoute: typeof ApiUsersUserIdResetPasswordRouteImport
      parentRoute: typeof ApiUsersUserIdRoute
    }
    '/api/tasks/$taskId/move': {
      id: '/api/tasks/$taskId/move'
      path: '/move'
      fullPath: '/api/tasks/$taskId/move'
      preLoaderRoute: typeof ApiTasksTaskIdMoveRouteImport
      parentRoute: typeof ApiTasksTaskIdRoute
    }
    '/api/tasks/$taskId/activity': {
      id: '/api/tasks/$taskId/activity'
      path: '/activity'
      fullPath: '/api/tasks/$taskId/activity'
      preLoaderRoute: typeof ApiTasksTaskIdActivityRouteImport
      parentRoute: typeof ApiTasksTaskIdRoute
    }
    '/api/tags/$tagId/detach': {
      id: '/api/tags/$tagId/detach'
      path: '/detach'
      fullPath: '/api/tags/$tagId/detach'
      preLoaderRoute: typeof ApiTagsTagIdDetachRouteImport
      parentRoute: typeof ApiTagsTagIdRoute
    }
    '/api/tags/$tagId/attach': {
      id: '/api/tags/$tagId/attach'
      path: '/attach'
      fullPath: '/api/tags/$tagId/attach'
      preLoaderRoute: typeof ApiTagsTagIdAttachRouteImport
      parentRoute: typeof ApiTagsTagIdRoute
    }
    '/api/realtime/projects/$projectId': {
      id: '/api/realtime/projects/$projectId'
      path: '/api/realtime/projects/$projectId'
      fullPath: '/api/realtime/projects/$projectId'
      preLoaderRoute: typeof ApiRealtimeProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$projectId/files': {
      id: '/api/projects/$projectId/files'
      path: '/files'
      fullPath: '/api/projects/$projectId/files'
      preLoaderRoute: typeof ApiProjectsProjectIdFilesRouteImport
      parentRoute: typeof ApiProjectsProjectIdRoute
    }
    '/api/projects/$projectId/archive': {
      id: '/api/projects/$projectId/archive'
      path: '/archive'
      fullPath: '/api/projects/$projectId/archive'
      preLoaderRoute: typeof ApiProjectsProjectIdArchiveRouteImport
      parentRoute: typeof ApiProjectsProjectIdRoute
    }
    '/api/projects/$projectId/activity': {
      id: '/api/projects/$projectId/activity'
      path: '/activity'
      fullPath: '/api/projects/$projectId/activity'
      preLoaderRoute: typeof ApiProjectsProjectIdActivityRouteImport
      parentRoute: typeof ApiProjectsProjectIdRoute
    }
    '/api/notifications/$notificationId/read': {
      id: '/api/notifications/$notificationId/read'
      path: '/api/notifications/$notificationId/read'
      fullPath: '/api/notifications/$notificationId/read'
      preLoaderRoute: typeof ApiNotificationsNotificationIdReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes/$noteId/secret': {
      id: '/api/notes/$noteId/secret'
      path: '/secret'
      fullPath: '/api/notes/$noteId/secret'
      preLoaderRoute: typeof ApiNotesNoteIdSecretRouteImport
      parentRoute: typeof ApiNotesNoteIdRoute
    }
    '/api/files/$fileId/download': {
      id: '/api/files/$fileId/download'
      path: '/api/files/$fileId/download'
      fullPath: '/api/files/$fileId/download'
      preLoaderRoute: typeof ApiFilesFileIdDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clients/$clientId/activity': {
      id: '/api/clients/$clientId/activity'
      path: '/activity'
      fullPath: '/api/clients/$clientId/activity'
      preLoaderRoute: typeof ApiClientsClientIdActivityRouteImport
      parentRoute: typeof ApiClientsClientIdRoute
    }
    '/api/tasks/$taskId/comments/': {
      id: '/api/tasks/$taskId/comments/'
      path: '/comments'
      fullPath: '/api/tasks/$taskId/comments'
      preLoaderRoute: typeof ApiTasksTaskIdCommentsIndexRouteImport
      parentRoute: typeof ApiTasksTaskIdRoute
    }
    '/api/projects/$projectId/members/': {
      id: '/api/projects/$projectId/members/'
      path: '/members'
      fullPath: '/api/projects/$projectId/members'
      preLoaderRoute: typeof ApiProjectsProjectIdMembersIndexRouteImport
      parentRoute: typeof ApiProjectsProjectIdRoute
    }
    '/api/projects/$projectId/members/$userId': {
      id: '/api/projects/$projectId/members/$userId'
      path: '/members/$userId'
      fullPath: '/api/projects/$projectId/members/$userId'
      preLoaderRoute: typeof ApiProjectsProjectIdMembersUserIdRouteImport
      parentRoute: typeof ApiProjectsProjectIdRoute
    }
  }
}

interface AppClientsRouteRouteChildren {
  AppClientsClientIdRoute: typeof AppClientsClientIdRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
}

const AppClientsRouteRouteChildren: AppClientsRouteRouteChildren = {
  AppClientsClientIdRoute: AppClientsClientIdRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
}

const AppClientsRouteRouteWithChildren = AppClientsRouteRoute._addFileChildren(
  AppClientsRouteRouteChildren,
)

interface AppProjectsProjectIdRouteRouteChildren {
  AppProjectsProjectIdBoardRoute: typeof AppProjectsProjectIdBoardRoute
  AppProjectsProjectIdFilesRoute: typeof AppProjectsProjectIdFilesRoute
  AppProjectsProjectIdNotesRoute: typeof AppProjectsProjectIdNotesRoute
  AppProjectsProjectIdTasksRoute: typeof AppProjectsProjectIdTasksRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
}

const AppProjectsProjectIdRouteRouteChildren: AppProjectsProjectIdRouteRouteChildren =
  {
    AppProjectsProjectIdBoardRoute: AppProjectsProjectIdBoardRoute,
    AppProjectsProjectIdFilesRoute: AppProjectsProjectIdFilesRoute,
    AppProjectsProjectIdNotesRoute: AppProjectsProjectIdNotesRoute,
    AppProjectsProjectIdTasksRoute: AppProjectsProjectIdTasksRoute,
    AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
  }

const AppProjectsProjectIdRouteRouteWithChildren =
  AppProjectsProjectIdRouteRoute._addFileChildren(
    AppProjectsProjectIdRouteRouteChildren,
  )

interface AppProjectsRouteRouteChildren {
  AppProjectsProjectIdRouteRoute: typeof AppProjectsProjectIdRouteRouteWithChildren
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppProjectsRouteRouteChildren: AppProjectsRouteRouteChildren = {
  AppProjectsProjectIdRouteRoute: AppProjectsProjectIdRouteRouteWithChildren,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppProjectsRouteRouteWithChildren =
  AppProjectsRouteRoute._addFileChildren(AppProjectsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppClientsRouteRoute: typeof AppClientsRouteRouteWithChildren
  AppProjectsRouteRoute: typeof AppProjectsRouteRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotesRoute: typeof AppNotesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppClientsRouteRoute: AppClientsRouteRouteWithChildren,
  AppProjectsRouteRoute: AppProjectsRouteRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppNotesRoute: AppNotesRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ApiClientsClientIdRouteChildren {
  ApiClientsClientIdActivityRoute: typeof ApiClientsClientIdActivityRoute
}

const ApiClientsClientIdRouteChildren: ApiClientsClientIdRouteChildren = {
  ApiClientsClientIdActivityRoute: ApiClientsClientIdActivityRoute,
}

const ApiClientsClientIdRouteWithChildren =
  ApiClientsClientIdRoute._addFileChildren(ApiClientsClientIdRouteChildren)

interface ApiNotesNoteIdRouteChildren {
  ApiNotesNoteIdSecretRoute: typeof ApiNotesNoteIdSecretRoute
}

const ApiNotesNoteIdRouteChildren: ApiNotesNoteIdRouteChildren = {
  ApiNotesNoteIdSecretRoute: ApiNotesNoteIdSecretRoute,
}

const ApiNotesNoteIdRouteWithChildren = ApiNotesNoteIdRoute._addFileChildren(
  ApiNotesNoteIdRouteChildren,
)

interface ApiProjectsProjectIdRouteChildren {
  ApiProjectsProjectIdActivityRoute: typeof ApiProjectsProjectIdActivityRoute
  ApiProjectsProjectIdArchiveRoute: typeof ApiProjectsProjectIdArchiveRoute
  ApiProjectsProjectIdFilesRoute: typeof ApiProjectsProjectIdFilesRoute
  ApiProjectsProjectIdMembersUserIdRoute: typeof ApiProjectsProjectIdMembersUserIdRoute
  ApiProjectsProjectIdMembersIndexRoute: typeof ApiProjectsProjectIdMembersIndexRoute
}

const ApiProjectsProjectIdRouteChildren: ApiProjectsProjectIdRouteChildren = {
  ApiProjectsProjectIdActivityRoute: ApiProjectsProjectIdActivityRoute,
  ApiProjectsProjectIdArchiveRoute: ApiProjectsProjectIdArchiveRoute,
  ApiProjectsProjectIdFilesRoute: ApiProjectsProjectIdFilesRoute,
  ApiProjectsProjectIdMembersUserIdRoute:
    ApiProjectsProjectIdMembersUserIdRoute,
  ApiProjectsProjectIdMembersIndexRoute: ApiProjectsProjectIdMembersIndexRoute,
}

const ApiProjectsProjectIdRouteWithChildren =
  ApiProjectsProjectIdRoute._addFileChildren(ApiProjectsProjectIdRouteChildren)

interface ApiTagsTagIdRouteChildren {
  ApiTagsTagIdAttachRoute: typeof ApiTagsTagIdAttachRoute
  ApiTagsTagIdDetachRoute: typeof ApiTagsTagIdDetachRoute
}

const ApiTagsTagIdRouteChildren: ApiTagsTagIdRouteChildren = {
  ApiTagsTagIdAttachRoute: ApiTagsTagIdAttachRoute,
  ApiTagsTagIdDetachRoute: ApiTagsTagIdDetachRoute,
}

const ApiTagsTagIdRouteWithChildren = ApiTagsTagIdRoute._addFileChildren(
  ApiTagsTagIdRouteChildren,
)

interface ApiTasksTaskIdRouteChildren {
  ApiTasksTaskIdActivityRoute: typeof ApiTasksTaskIdActivityRoute
  ApiTasksTaskIdMoveRoute: typeof ApiTasksTaskIdMoveRoute
  ApiTasksTaskIdCommentsIndexRoute: typeof ApiTasksTaskIdCommentsIndexRoute
}

const ApiTasksTaskIdRouteChildren: ApiTasksTaskIdRouteChildren = {
  ApiTasksTaskIdActivityRoute: ApiTasksTaskIdActivityRoute,
  ApiTasksTaskIdMoveRoute: ApiTasksTaskIdMoveRoute,
  ApiTasksTaskIdCommentsIndexRoute: ApiTasksTaskIdCommentsIndexRoute,
}

const ApiTasksTaskIdRouteWithChildren = ApiTasksTaskIdRoute._addFileChildren(
  ApiTasksTaskIdRouteChildren,
)

interface ApiUsersUserIdRouteChildren {
  ApiUsersUserIdResetPasswordRoute: typeof ApiUsersUserIdResetPasswordRoute
  ApiUsersUserIdRoleRoute: typeof ApiUsersUserIdRoleRoute
}

const ApiUsersUserIdRouteChildren: ApiUsersUserIdRouteChildren = {
  ApiUsersUserIdResetPasswordRoute: ApiUsersUserIdResetPasswordRoute,
  ApiUsersUserIdRoleRoute: ApiUsersUserIdRoleRoute,
}

const ApiUsersUserIdRouteWithChildren = ApiUsersUserIdRoute._addFileChildren(
  ApiUsersUserIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiClientsClientIdRoute: ApiClientsClientIdRouteWithChildren,
  ApiCommentsCommentIdRoute: ApiCommentsCommentIdRoute,
  ApiNotesNoteIdRoute: ApiNotesNoteIdRouteWithChildren,
  ApiProfileAvatarRoute: ApiProfileAvatarRoute,
  ApiProfilePasswordRoute: ApiProfilePasswordRoute,
  ApiProjectsProjectIdRoute: ApiProjectsProjectIdRouteWithChildren,
  ApiRealtimeNotificationsRoute: ApiRealtimeNotificationsRoute,
  ApiTagsTagIdRoute: ApiTagsTagIdRouteWithChildren,
  ApiTasksTaskIdRoute: ApiTasksTaskIdRouteWithChildren,
  ApiUsersUserIdRoute: ApiUsersUserIdRouteWithChildren,
  ApiActivityIndexRoute: ApiActivityIndexRoute,
  ApiClientsIndexRoute: ApiClientsIndexRoute,
  ApiDashboardIndexRoute: ApiDashboardIndexRoute,
  ApiNotesIndexRoute: ApiNotesIndexRoute,
  ApiNotificationsIndexRoute: ApiNotificationsIndexRoute,
  ApiProfileIndexRoute: ApiProfileIndexRoute,
  ApiProjectsIndexRoute: ApiProjectsIndexRoute,
  ApiSearchIndexRoute: ApiSearchIndexRoute,
  ApiTagsIndexRoute: ApiTagsIndexRoute,
  ApiTasksIndexRoute: ApiTasksIndexRoute,
  ApiUsersIndexRoute: ApiUsersIndexRoute,
  ApiFilesFileIdDownloadRoute: ApiFilesFileIdDownloadRoute,
  ApiNotificationsNotificationIdReadRoute:
    ApiNotificationsNotificationIdReadRoute,
  ApiRealtimeProjectsProjectIdRoute: ApiRealtimeProjectsProjectIdRoute,
  ApiUsersMeThemeRoute: ApiUsersMeThemeRoute,
  ApiFilesFileIdIndexRoute: ApiFilesFileIdIndexRoute,
  ApiUsersMeIndexRoute: ApiUsersMeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
